# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2")  do |config|
  #Forward guest port 80 to host port 8080
config.vm.box="hashicorp/precise64"
config.vm.network "private_network", ip: "192.168.68.8"
config.vm.network :forwarded_port, guest: 80, host: 8080
#config.vm.forward_port 80, 8080
config.vm.provision :shell, :path => "bootstrap.sh"
end
