# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Forward guest port 80 to host port 4567
config.vm.box="hashicorp/precise64"
  config.vm.forward_port 80, 4567
config.vm.provision :shell, :path => "bootstrap.sh"
end
